### ISSUE TITLE
JSONDecodeError when providing event body python3.6

### ISSUE THREAD

**Issue by spyoungtech** [lambci/docker-lambda#100]
The command
```
docker run -v ${PWD}:/var/task --rm lambci/lambda:python3.6 lambda_function.lambda_handler '{"foo": "bar"}'
```

Produces the following error:

```
START RequestId: 72011235-1b83-4b03-af02-e83c0806b3c4 Version: $LATEST
Unable to parse input as json: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

END RequestId: 72011235-1b83-4b03-af02-e83c0806b3c4
REPORT RequestId: 72011235-1b83-4b03-af02-e83c0806b3c4 Duration: 15 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 19 MB

{"errorMessage": "Expecting value: line 1 column 1 (char 0)", "errorType": "JSONDecodeError", "stackTrace": [["/var/lang/lib/python3.6/json/__init__.py", 354, "loads", "return _default_decoder.decode(s)"], ["/var/lang/lib/python3.6/json/decoder.py", 339, "decode", "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"], ["/var/lang/lib/python3.6/json/decoder.py", 357, "raw_decode", "raise JSONDecodeError(\"Expecting value\", s, err.value) from None"]]}
```
I also tried using the environment variable with the `-e` option with the same result
Possibly a windows specific issue. I've also tried using a powershell script that loads a string from a json file like

```
$EVENT_BODY = Get-Content .\test_event.json -Raw
docker run -v ${PWD}:/var/task --rm lambci/lambda:python3.6 lambda_function.lambda_handler $EVENT_BODY
```
I get a slightly different error

```
{"errorMessage": "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)", "errorType": "JSONDecodeError", "stackTrace": [["/var/lang/lib/python3.6/json/__init__.py", 354, "loads", "return _default_decoder.decode(s)"], ["/var/lang/lib/python3.6/json/decoder.py", 339, "decode", "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"], ["/var/lang/lib/python3.6/json/decoder.py", 355, "raw_decode", "obj, end = self.scan_once(s, idx)"]]}
```

However, if I write the event body like so `"{\"foo\": \"bar\"}"`, that works fine.

**Comment by mhart** [comment]
Yeah, I'm sure it's just an issue with how you're escaping characters for the command line on Windows.

I don't think there's any bug in docker-lambda here – but feel free to reopen if you think there is.
