### ISSUE TITLE
Build failed after download new docker image 

### ISSUE THREAD

**Issue by at-bachhuynh** [lambci/docker-lambda#217]
Hi all,
Is there any one like me, yesterday I still build OK, 
But today, I see my pc fetch new lambda image, and after that build failed.

sam build --use-container        

```  
starting Build inside a container
Building resource 'TothemoonFunction'

Fetching lambci/lambda:build-python2.7 Docker container image...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Mounting /Users/XXXX/Documents/Project/XXXXX/XXX-XXX/XXXX as /tmp/samcli/source:ro,delegated inside runtime container

Build Failed
Running PythonPipBuilder:ResolveDependencies
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
```

Update:

Run build with debug

```
sam build --use-container --debug        
                                                                                                                             
Using SAM Template at /Users/xxxx/Documents/Project/xxxx/xxxx/template.yaml
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='xxxxFunction' and CodeUri=xxxx_new_platform/'
Building resource 'xxxxFunction'

Fetching lambci/lambda:build-python2.7 Docker container image......
Mounting /Users/XXX/Documents/Project/Org-XXXX/tothemoon-saturn/xxxx as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
PythonPipBuilder:ResolveDependencies raised unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 27, in execute
    pip = SubprocessPip(osutils=os_utils, python_exe=python_path)
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 555, in __init__
    import_string = pip_import_string(python_exe=self.python_exe)
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/compat.py", line 16, in pip_import_string
    pip_major_version = int(pip_version.split('.')[0])
ValueError: invalid literal for int() with base 10: ''
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 27, in execute
    pip = SubprocessPip(osutils=os_utils, python_exe=python_path)
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 555, in __init__
    import_string = pip_import_string(python_exe=self.python_exe)
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/compat.py", line 16, in pip_import_string
    pip_major_version = int(pip_version.split('.')[0])
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/__main__.py", line 137, in main
    mode=params.get('mode', None))
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/builder.py", line 115, in build
    return workflow.run()
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 65, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 263, in run
    reason=str(ex))
aws_lambda_builders.exceptions.WorkflowUnknownError: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 7455, 'exitReason': 'UserException', 'exitCode': 1, 'requestId': '521f0abf-ea84-4df7-9218-ca41f78d5c2c', 'installationId': '597395f9-cb76-4160-a946-6e816850e756', 'sessionId': 'f97a926a-67a7-4102-ae75-7a0c52bac0a0', 'executionEnvironment': 'CLI', 'pyversion': '3.7.5', 'samcliVersion': '0.30.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
```

**Comment by mhart** [comment]
Apologies for this – I had wanted to update to the latest AWS SAM CLI on the image which required Python 3.x. I didn't realize that aws-lambda-builders would just try to build in the same Python version.

I've pushed up a fix for this, please try it out

**Comment by at-bachhuynh** [comment]
Thank you so much @mhart 
I really appreciated !!!
