### ISSUE TITLE
Ruby Build Images Missing Rake

### ISSUE THREAD

**Issue by dlahn** [lambci/docker-lambda#268]
`rake` is not available in the build images, but it is available in the runtime images.

```
└─(16:31:49 on master)──> docker run -it --rm lambci/lambda:build-ruby2.5 sh                                    
sh-4.2# rake
Traceback (most recent call last):
	2: from /var/lang/bin/rake:23:in `<main>'
	1: from /var/lang/lib/ruby/site_ruby/2.5.0/rubygems.rb:294:in `activate_bin_path'
/var/lang/lib/ruby/site_ruby/2.5.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake (Gem::GemNotFoundException)
```

This is present in 2.5 and 2.7.

**Comment by mhart** [comment]
Hmmm. It's there:
```
/var/lang/lib/ruby/gems/2.5.0/gems/rake-12.3.3
```

Just need to figure out why it's not being found

**Comment by lloydpick** [comment]
We've worked it out, the GEM_PATH is incorrect, just making a PR now.

**Comment by dlahn** [comment]
PR: https://github.com/lambci/docker-lambda/pull/270

**Comment by mhart** [comment]
Fixed! Thanks for raising 👍
