### ISSUE TITLE
_sqlite3 error

### ISSUE THREAD

**Issue by olivier-jobable** [lambci/docker-lambda#36]
repro:
`docker run -ti lambci/lambda:build-python3.6 bash`
`bash-4.2# pip3 install nltk`
.....
`Successfully installed nltk-3.2.2`

bash-4.2# python -c "import nltk"

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lang/lib/python3.6/site-packages/nltk/__init__.py", line 137, in <module>
    from nltk.stem import *
  File "/var/lang/lib/python3.6/site-packages/nltk/stem/__init__.py", line 29, in <module>
    from nltk.stem.snowball import SnowballStemmer
  File "/var/lang/lib/python3.6/site-packages/nltk/stem/snowball.py", line 24, in <module>
    from nltk.corpus import stopwords
  File "/var/lang/lib/python3.6/site-packages/nltk/corpus/__init__.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "/var/lang/lib/python3.6/site-packages/nltk/corpus/reader/__init__.py", line 105, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "/var/lang/lib/python3.6/site-packages/nltk/corpus/reader/panlex_lite.py", line 15, in <module>
    import sqlite3
  File "/var/lang/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/var/lang/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

I found that version in the container but nothing for python3.6 or 3.4
/usr/lib64/python2.7/lib-dynload/_sqlite3.so

I have installed sqlite-devel (yum install sqlite-devel) before rebuilding python but still no luck.

I am out of ideas now.

**Comment by olivier-jobable** [comment]
After some testing, it does work when I use python2.7 image.

**Comment by rolando** [comment]
The PR #39 address this issue.

**Comment by mhart** [comment]
This should be fixed thanks to #39
