### ISSUE TITLE
Error when running lambci/lambda:python3.6

### ISSUE THREAD

**Issue by jonatasbaldin** [lambci/docker-lambda#43]
Running this command `docker run -v "$PWD":/var/task lambci/lambda:python3.6` with the file in `examples/python/lambda_function.py`, I got this error: 

```
$ docker run -v "$PWD":/var/task lambci/lambda:python3.6

START RequestId: 5218ac6f-6b85-475c-a8e1-0574ab7f1509 Version: $LATEST
Traceback (most recent call last):
  File "/var/runtime/awslambda/bootstrap.py", line 514, in <module>
    main()
  File "/var/runtime/awslambda/bootstrap.py", line 503, in main
    init_handler, request_handler = _get_handlers(handler, mode)
  File "/var/runtime/awslambda/bootstrap.py", line 29, in _get_handlers
    lambda_runtime.report_user_init_start()
AttributeError: module 'runtime' has no attribute 'report_user_init_start'
```

Do you have any ideia?

**Comment by mhart** [comment]
This should be fixed as of 838d5f65ced3ed868fddce2ba55e6f3043521856 which just finished building
