### ISSUE TITLE
unable to pass EVENT BODY to RUN python27

### ISSUE THREAD

**Issue by soma28208d51** [lambci/docker-lambda#47]
Unable to run the example Python lambda function with `docker run -v "$PWD":/var/task lambci/lambda:python2.7 -e AWS_LAMBDA_EVENT_BODY='{}' or docker run -v "$PWD":/var/task lambci/lambda:python2.7 -e AWS_LAMBDA_EVENT_BODY={} or docker run -v "$PWD":/var/task lambci/lambda:python2.7 -e AWS_LAMBDA_EVENT_BODY '{}' docker run -v "$PWD":/var/task lambci/lambda:python2.7 -e AWS_LAMBDA_EVENT_BODY {}`  

Fails with 
```
START RequestId: b2d49b12-52d6-4ad0-8b21-93faf7c48dec Version: $LATEST
Unable to parse input as json: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

END RequestId: b2d49b12-52d6-4ad0-8b21-93faf7c48dec
REPORT RequestId: b2d49b12-52d6-4ad0-8b21-93faf7c48dec Duration: 0 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 14 MB
{"stackTrace": [["/usr/lib64/python2.7/json/__init__.py", 339, "loads", "return _default_decoder.decode(s)"], ["/usr/lib64/python2.7/json/decoder.py", 364, "decode", "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"], ["/usr/lib64/python2.7/json/decoder.py", 382, "raw_decode", "raise ValueError(\"No JSON object could be decoded\")"]], "errorType": "ValueError", "errorMessage": "No JSON object could be decoded"}
```

**Comment by mhart** [comment]
@soma28208d51 does the following work for you?

```
docker run -v "$PWD":/var/task lambci/lambda:python2.7 lambda_function.lambda_handler '{"whatever": "things"}'
```

**Comment by mhart** [comment]
If you do want to use environment variables, they need to come before the image, not after:

```
docker run -e AWS_LAMBDA_EVENT_BODY='{"hello":"whatever"}' -v "$PWD":/var/task lambci/lambda:python2.7
```
