### ISSUE TITLE
System.Data.SqlClient not supported exception while executing dotnetcore2.0 lambda

### ISSUE THREAD

**Issue by rafanoronha** [lambci/docker-lambda#76]
Hey,
Found lambci through this comment on aws-sam-local project:
https://github.com/awslabs/aws-sam-local/issues/144#issuecomment-334094287

I'm developing a c# lambda which is already working fine on aws lambda.
Just configured the sam local required stuff and when I run sam local invoke, the handler gets called but a error happens when it tries to talk to a sql server through EF core. Error pasted below.

Wondering if this might be related with https://github.com/dotnet/corefx/issues/24229.

```
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<ValidateUserInternal>d__169.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at My.Handler.<<HandleMessage>b__5_0>d.MoveNext() in myworkdir\My\Handler.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at My.Handler.<HandleMessage>d__5.MoveNext() in myworkdir\My\Handler.cs:line 123

Unhandled Exception: System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()
```

**Comment by hounddog22030** [comment]
Hi.  Did you ever find any solution to this issue?  I am experiencing the same issue, same call stack on AWS Lambda as well.  Is your "data" assembly .net standard or .net core?

**Comment by rafanoronha** [comment]
Hey @hounddog22030 
Nope, unfortunately this is not something I'm commited to right now.
My lambda assembly targets netcoreapp2.0 and spans entities from a netstandard1.0 assembly.

**Comment by mrcunninghamz** [comment]
I am running into this now. Anyone?

**Comment by hounddog22030** [comment]
I bulldogged through updating all packages to the highest acceptable levels (for Lambda) and got rid of the problem.

**Comment by mrcunninghamz** [comment]
@hounddog22030 what version of System.Data.SqlClient did you end up with? I don't want to go lower than 4.5.1 because of other dependencies, but will make a change if I know for sure a version works in that environment. I am actually running netcoreapp2.1 in my template.yaml for runtime.

**Comment by mrcunninghamz** [comment]
also as a note: This lambda works fine when I publish it to AWS... so I think the image lambci/lambda:dotnetcore2.1  might be behind whatever is running in aws.

**Comment by hounddog22030** [comment]
Let me check tonight. I jut updated all Nuget packages last night as well.

**Comment by mhart** [comment]
There are definitely some differences between how docker-lambda invokes the .NET runtimes and how Lambda does it on production. Unfortunately, due to the nature of .NET DLLs, it's very hard to reverse engineer this process.

Lambda executes:
```
/var/runtime/awslambda --netcore /var/lang --runtime /var/runtime --task /var/task
```
which appears to be a native binary that then executes a child process similar to:
```
dotnet exec \
  --depsfile /var/task/my_function.deps.json \
  --runtimeconfig /var/task/my_function.runtimeconfig.json \
  /var/runtime/Bootstrap.dll \
  --invokeid af962ae8-71a2-4919-942d-fcf327d8680d --flag 0 \
  --handler my_function::my_function.Function::FunctionHandler \
  --errorcode
```

We try to wrap as much of the Bootstrap as we can using a [MockBootstrap](https://github.com/lambci/docker-lambda/blob/master/dotnetcore2.0/run/MockBootstraps/Program.cs), but there are no doubt gaps in there, especially with relation to dependencies. Even `dotnet exec` itself isn't documented.

I've updated the dotnetcore images to include the latest DLLs from Lambda, but any help in making the bootstrap process more similar to production would be greatly appreciated

**Comment by mhart** [comment]
This should be fixed thanks to the resolution in https://github.com/lambci/docker-lambda/issues/177 – please try again!
